CREATE TABLE EQUIPAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COD_EQUIP VARCHAR(9),
    MODELO VARCHAR(30),
    ANO_FABRICACAO INT,
    CONSUMO_COMBUSTIVEL DECIMAL(10,2),
    EMISSAO_CO2_HORA DECIMAL(10,2),
	HORAS_TRABALHADAS DECIMAL (10,2)
);


CREATE TABLE CATEGORIA (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50),
DESCRICAO VARCHAR(200)
);


ALTER TABLE EQUIPAMENTO
ADD COLUMN CATEGORIA_ID,
ADD FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID);


CREATE TABLE EMISSAO_HISTORICO (
EQUIPAMENTO_ID INT AUTO_INCREMENT,
DATA_HORA DATETIME,
EMISSAO_CO2 DECIMAL(10,2),
PRIMARY KEY (EQUIPAMENTO_ID, DATA_HORA),
FOREIGN KEY (EQUIPAMENTO_ID) REFERENCES EQUIPAMENTO(ID)
);

CREATE TABLE REGISTRO_USO (
EQUIPAMENTO_ID INT AUTO_INCREMENT,
DATA_HORA_INICIO DATETIME,
DATA_HORA_FIM DATETIME,
PRIMARY KEY (EQUIPAMENTO_ID, DATA_HORA_INICIO),
FOREIGN KEY (EQUIPAMENTO_ID) REFERENCES EQUIPAMENTO(ID)
);
